server:
  port: 8081
spring:
  application:
    name: userservice
  config:
    import: "optional:configserver:http://localhost:8888"
  boot:
    admin:
      client:
        url: http://localhost:1111/
  profiles:
    active: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
app:
  version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    path=: /api-docs