server:
  port: 8081
app:
  config:
    name: USERSERVICE
    version: 1.0
spring:
  application:
    name: userservice
  config:
      import: "optional:configserver:http://localhost:8888"
  boot:
    admin:
      client:
        url: http://localhost:1111/
  profiles:
    active: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'